version: '3.8'

services:
  web:
    build:
      dockerfile: docker/web/Dockerfile
      context: .
      args:
        PHP_VERSION: 8.0
        APP_ENV: ${APP_ENV}
        VARNISH_HOST: ${VARNISH_HOST}
        APACHE_HOST: ${APACHE_HOST}
    working_dir: /var/www/html
    networks:
      carranker:
        ipv4_address: ${APACHE_HOST}
    container_name: carranker
    ports:
      - 80:80
      - 8181:8181
      - 443:443
      - 25:25
  redis:
    build:
      dockerfile: docker/redis/Dockerfile
      context: .
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    container_name: carranker-redis
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}
    networks:
      carranker:
        ipv4_address: ${REDIS_HOST}
  elasticsearch:
    build:
      dockerfile: docker/elasticsearch/Dockerfile
      context: .
      args:
        ELASTICSEARCH_HOST: ${ELASTICSEARCH_HOST}
    container_name: carranker-elasticsearch
    environment:
      - node.name=carranker-elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=
      - cluster.initial_master_nodes=carranker-elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - ${ELASTICSEARCH_PORT}:${ELASTICSEARCH_PORT}
    networks:
      carranker:
        ipv4_address: ${ELASTICSEARCH_HOST}
  varnish:
    build:
      dockerfile: docker/varnish/Dockerfile
      context: .
      args:
        APACHE_HOST: ${APACHE_HOST}
    ports:
      - 8080:80
    container_name: carranker-varnish
    networks:
      carranker:
        ipv4_address: ${VARNISH_HOST}
  database:
    image: mysql:8.0
    ports:
      - ${DB_PORT}:${DB_PORT}
    container_name: carranker-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysqldata:/var/lib/mysql
    entrypoint:
      sh -c "
      echo 'CREATE DATABASE IF NOT EXISTS ${DB_DATABASE}; CREATE DATABASE IF NOT EXISTS ${TEST_DATABASE};' > /docker-entrypoint-initdb.d/init.sql;
      /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      "
    networks:
      carranker:
        ipv4_address: ${DB_HOST}

volumes:
  esdata:
    driver: local
  mysqldata:
    driver: local

networks:
  carranker:
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}
