version: '3.8'

services:
  frontend:
    build:
      dockerfile: docker/web/Dockerfile
      context: .
      args:
        uid: ${UID}
        upass: ${UPASS}
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./config/apache2.conf:/etc/apache2/apache2.conf
      - ./config/php-apache2.ini:/etc/php/7.4/apache2/conf.d/php-apache2.ini
      - ./config/php-cli.ini:/etc/php/7.4/cli/conf.d/php-cli.ini
    networks:
      carranker:
    container_name: carranker
    ports:
      - "80:80"
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
      - PHP_IDE_CONFIG=serverName=carranker
  backend:
    build:
      dockerfile: docker/web/Dockerfile
      context: .
      args:
        uid: ${UID}
        upass: ${UPASS}
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./config/apache2.conf:/etc/apache2/apache2.conf
      - ./config/php-apache2.ini:/etc/php/7.4/apache2/conf.d/php-apache2.ini
      - ./config/php-cli.ini:/etc/php/7.4/cli/conf.d/php-cli.ini
    networks:
      carranker:
    container_name: cms.carranker
    ports:
      - "8080:80"
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/wordpress
      - PHP_IDE_CONFIG=serverName=cms.carranker
  redis:
    image: redis:5.0
    ports:
      - "6379:6379"
    container_name: carranker-redis
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
      - ./logs/redis/:/var/log/redis/
    networks:
      carranker:
        ipv4_address: ${REDIS_HOST}
  database:
    image: mysql:8.0
    ports:
      - "3306:3306"
    container_name: carranker-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_DEVUSER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    entrypoint:
      sh -c "
      echo 'CREATE DATABASE IF NOT EXISTS ${DB_DATABASE}; CREATE DATABASE IF NOT EXISTS ${TEST_DATABASE};' > /docker-entrypoint-initdb.d/init.sql;
      /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      "
    networks:
      carranker:
        ipv4_address: ${DB_HOST}
  selenium:
    image: selenium/standalone-chrome
    container_name: carranker-selenium
    networks:
      carranker:

networks:
  carranker:
    ipam:
      driver: default
      config:
        - subnet: "172.21.0.0/24"