services:
  web:
    volumes:
      - ./public/.well-known/acme-challenge:/var/www/html/public/.well-known/acme-challenge
    restart: always
  elastic:
    restart: always
  redis:
    restart: always
  varnish:
    restart: always
  database:
    restart: always
